import { CounterpartiesIcon, CrownIcon, DeliveryIcon, EmployeeIcon, ExchangeIcon, FaqIcon, FavoriteIcon, FileIcon, FinanceIcon, GoodIcon, IdCardIcon, ReportIcon, SettingsIcon, ShopIcon } from "@assets/index";

export const SIDEBAR_CATEGORIES = [
    { title: 'Избранное', id: 'favorite', icon: FavoriteIcon },
    { title: 'Розничные продажи', id: 'retail-sales', icon: ShopIcon },
    { title: 'Товары и склады', id: 'goods', icon: GoodIcon },
    { title: 'Сотрудники', id: 'employees', icon: EmployeeIcon },
    { title: 'Прейскурант', id: 'price-list', icon: FileIcon },
    { title: 'Финансы', id: 'finance', icon: FinanceIcon },
    { title: 'Контрагенты', id: 'counterparties', icon: CounterpartiesIcon },
    { title: 'Отчеты', id: 'reports', icon: ReportIcon },
    { title: 'Дисконтная система', id: 'discount', icon: IdCardIcon },
    { title: 'Обмен данными', id: 'exchange-data', icon: ExchangeIcon },
    { title: 'Администрирование', id: 'admin-panel', icon: CrownIcon },
    { title: 'Доставка', id: 'delivery', icon: DeliveryIcon },
    { title: 'Настройки', id: 'settings', icon: SettingsIcon },
    { title: 'Помощь', id: 'help', icon: FaqIcon },
];

export const SIDEBAR_SUBCATEGORIES: {[key: string]: {title: string}[]} = {
    "favorite": [],
    "retail-sales": [
        { title: 'Кассовые продажи, смены' },
        { title: 'OLAP отчет по продажам и по проводкам' },
        { title: 'Типы внесений и изъятий' },
        { title: 'Типы оплат' },
        { title: 'Типы заказов' },
        { title: 'Видеонаблюдение' },
        { title: 'Банкеты, резервы, доставки' },
        { title: 'ABC XYZ анализ' },
      ],
      "goods": [
        { title: 'Товары' },
        { title: 'Блюда' },
        { title: 'Заготовки' },
        { title: 'Модификации' },
        { title: 'Номенклатура' },
        { title: 'Группы аллергенов' },
        { title: 'Единицы измерения' },
        { title: 'Бухгалтерские категории' },
        { title: 'Признаки расчета' },
        { title: 'Склады, поставщики' },
        { title: 'Накладные' },
        { title: 'Инвентаризации' },
        { title: 'Акты списания' },
        { title: 'Акты переработки' },
        { title: 'Остатки на складах' },
        { title: 'Движение товара' },
        { title: 'Отчет о вхождении товара в блюда' },
      ],
      "production-logistics": [
        { title: 'Заказ блюд и продуктов' },
        { title: 'Отчет о закупках' },
      ],
      "employees": [
        { title: 'Список сотрудников' },
        { title: 'Должности' },
        { title: 'Типы смен' },
        { title: 'Типы явок' },
        { title: 'Удержания' },
        { title: 'Начисления' },
        { title: 'Расписание' },
        { title: 'Планирование расписания' },
        { title: 'Персональный отчет' },
        { title: 'Журнал явки' },
        { title: 'Платежные ведомости' },
      ],
      "price-list": [
        { title: 'Быстрое меню' },
        { title: 'Прейскуранты товаров и услуг' },
        { title: 'Периоды действия' },
      ],
      "finance": [
        { title: 'План счетов' },
        { title: 'Акты приема услуг' },
        { title: 'Акты оказания услуг' },
        { title: 'Отчет о прибылях и убытках' },
        { title: 'Отчет о движении денег' },
        { title: 'Задолженность перед контрагентами' },
        { title: 'Прогноз продаж' },
      ],
      "counterparties": [
        { title: 'Гости банкетов и резервов' },
      ],
      "reports": [
        { title: 'Все возможные отчеты' },
      ],
      "discount": [
        { title: 'Клубные карты' },
        { title: 'Скидки и надбавки' },
      ],
      "administration": [
        { title: 'Настройки торгового предприятия' },
        { title: 'Схемы залов' },
        { title: 'Настройки оборудования' },
        { title: 'Права доступа' },
        { title: 'Шаблоны печатных форм' },
        { title: 'Шаблоны чеков' },
      ],
    "exchange-data": [],
    "admin-panel": [],
    "delivery": [],
    "settings": [],
    "help": [],
}
